### ISSUE TITLE
Understandability

### ISSUE THREAD

**Issue by vikramdurai** [Muhammad-Salman-Sheikh/Language#3]
in `code.js`:
```js
i = _ => JSON.stringify(_);
```

^ should be:
```js
i = JSON.stringify;
```

since `i` is simply an alias to JSON.stringify.

**Comment by Muhammad-Salman-Sheikh** [comment]
@vikramdurai : Thanks . Will update it

**Comment by vikramdurai** [comment]
I submitted pull request.

**Comment by Muhammad-Salman-Sheikh** [comment]
@vikramdurai : Thanks.

**Comment by Muhammad-Salman-Sheikh** [comment]
@vikramdurai : pull request was merged. Thanks a lot
