### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by vikramdurai** [Muhammad-Salman-Sheikh/Language#6]
There should be a `LICENSE.txt` file containing a software license. If you've never heard of a software license, go to https://choosealicense.com/.

**Comment by Muhammad-Salman-Sheikh** [comment]
@vikramdurai  : Hi , I am aware of what a software license is. I will add a license any suggestions ?

**Comment by Muhammad-Salman-Sheikh** [comment]
@vikramdurai : I added a license , not sure if it is right or what ?

**Comment by vikramdurai** [comment]
it's ok

**Comment by Muhammad-Salman-Sheikh** [comment]
@vikramdurai : Thanks
